---

- name: Install mysql
  command: kubectl apply -f -
  args:
    stdin: "{{ item }}"
  with_items:
    - "{{ lookup('template', 'configmap.yml') }}"
    - "{{ lookup('template', 'secret.yml') }}"
    - "{{ lookup('template', 'statefulset.yml') }}"
    - "{{ lookup('template', 'svc.yml') }}"
