apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app: mysql
type: Opaque
data:
  mysql-root-password: "{{ mysql_root_password | b64encode }}"
  mysql-password: "{{ mysql_password | b64encode }}"
  mysql-replication-password: "{{ mysql_replication_password | b64encode }}"
  